name: AutoIncrementTag

on:
  push:
    # branches: [ main ]
  workflow_dispatch:
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Extract latest tag number
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          BRANCHNAME=${{ github.ref_name }}
          echo "Got branch name: ${BRANCHNAME}"
          BUILDSUFFIX=$(git tag -l "${BRANCHNAME}.*" | awk -F. '{print $NF}' | sort -n - | tail -n 1)
          echo "Latest build suffix: ${BUILDSUFFIX}"
          NEWBUILDSUFFIX=$((${BUILDSUFFIX:--1} + 1))
          echo "New build suffix: ${NEWBUILDSUFFIX}"
          NEWTAG="${BRANCHNAME}.${NEWBUILDSUFFIX}"
          echo "Creating new tag: ${NEWTAG}"
          git tag -a "${NEWTAG}" -m "Auto-incremented tag"
          echo "Pushing tag ${NEWTAG} to origin"
          git push origin tag "${NEWTAG}"
          if [ $? -ne 0 ]; then
            echo "Failed to push tag ${NEWTAG}"
            exit 1
          fi
          echo "New tag ${NEWTAG} created and pushed successfully."
